[Be/#98] Feat: review question command
sgdevcamp2023/recycle pull request #256
Opened 2024-02-03 07:16 UTC by sso9594

🎫 연관 티켓 
---
#98 

🙏 작업
----
- 리뷰 command 모델의 question 도메인에 대한 Create, Update, Delete 를 구현했습니다.

💁‍♂️ 어떻게?
----
- Create에 경우 요청을 받게 되면 converter를 통해 usecase로 request를 넘겨 요청을 수행하도록 하였습니다.
  - 임시 저장의 경우 redis를 통해 캐시에 저장하는 방식으로 구현되어 있습니다. 
- Update에 경우 요청을 받게 되면 해당 요청에 대한 권한 및 유효성, 예외를 검사하고 jpa의 dirty checking을 통한 update를 수행하도록 구현하였습니다.
- Delete의 경우 요청을 받게되면 해당 요청에 대한 권한, 유효성 및 예외를 검사하고 수행하도록 구현하였습니다.
🙈 PR 참고 사항
----

📸 스크린샷
----

🤖 테스트 체크리스트
----
- [ ] 체크 미완료
- [x] 체크 완료

2024-02-11 14:43 UTC, belljun3395 commented
린트가 맞지 않는거 같네요.. 린트 맞처주세요!

2024-02-11 14:44 UTC, belljun3395 commented
예외를 한국어가 아닌 영어로 나타내기로 하였는데 한국어로 되어 있어 영어로 수정해야 할 것 같습니다.

2024-02-11 14:53 UTC, belljun3395 commented
몇몇 멤버의 자료형이 int로 선언하였던데 이유가 있나요?

2024-02-11 14:54 UTC, belljun3395 commented
createAt과 updatedAt을 request로 받는 이유가 따로 있나요? 그렇게 되면 프런트에서 해당 정보를 넘겨 받는다는 말인가요?

2024-02-11 15:04 UTC, belljun3395 commented
조회시 쿼리에서 deleted를 확인하는 것이 좋지 않을까요?

2024-02-11 15:20 UTC, belljun3395 commented
controller에서 ApiControllerExceptionHandler가 있는데 try-catch를 사용하여 처리한 이유가 있나요?

2024-02-11 15:23 UTC, belljun3395 requested changes

2024-02-11 15:23 UTC, belljun3395 commented on be/review-api/src/main/java/com/zzaug/review/domain/usecase/question/QuestionReqViewUseCase.java
> +public class QuestionReqViewUseCase {
다른 클래스 명들과 통일성을 위해 Req보다 Request 전부 적는 것이 어떨까요?

2024-02-11 15:23 UTC, belljun3395 commented on be/review-api/src/main/java/com/zzaug/review/domain/usecase/question/QuestionReqViewUseCase.java
> +		LinkedHashSet<Long> reqQuestionIds = new LinkedHashSet<>();
list를 linkedHashSet으로 바꾸어 코드를 작성한 이유가 무엇인가요?

2024-02-11 15:23 UTC, belljun3395 commented on be/review-api/src/main/java/com/zzaug/review/domain/usecase/question/QuestionTempViewUseCase.java
> +			System.out.println(request.getTempId());
log로 수정하는 것이 좋을 것 같아요

2024-02-11 15:23 UTC, belljun3395 commented on be/review-api/src/main/java/com/zzaug/review/domain/usecase/question/QuestionTempCreateUseCase.java
> +		questionTempRepository.save(QuestionTempEntityConverter.from(questionTemp));
별도의 검증 로직은 필요하지 않나요?

2024-02-11 15:23 UTC, belljun3395 commented on be/web/src/main/java/com/zzaug/web/support/MessageCode.java
> +	RESOURCE_NOT_FOUND("resource.not.found", "해당 리소스를 찾을 수 없습니다."),
모두 사용되지 않는데 추가된 이유가 무엇인가요?

2024-02-11 15:23 UTC, belljun3395 commented on be/review-api/src/main/java/com/zzaug/review/entity/member/ReviewerListEntity.java
> +public class ReviewerListEntity {
해당 엔티티는 createdAt, updatedAt, deletedAt이 필요없나요?

2024-02-11 15:23 UTC, belljun3395 commented on be/review-api/src/main/java/com/zzaug/review/entity/question/QuestionEntity.java
> +	private boolean isDeleted;
해당 멤버는 @Column을 따로 지정하지 않은 이유가 있나요?

2024-02-11 15:23 UTC, belljun3395 commented on be/review-api/src/main/java/com/zzaug/review/entity/question/QuestionEntity.java
> +	@ColumnDefault("false")
객체 생성시 기본값을 설정하는 것이 아닌 @ColumnDefault로 기본 값을 설정하신 이유가 있나요?

2024-02-11 15:23 UTC, belljun3395 commented on be/review-api/src/main/java/com/zzaug/review/entity/question/QuestionRequestEntity.java
> +public class QuestionRequestEntity {
해당 엔티티는 createdAt, updatedAt, deletedAt이 필요없나요?

2024-02-11 15:23 UTC, belljun3395 commented on be/review-api/src/main/java/com/zzaug/review/entity/question/QuestionTempEntity.java
> +public class QuestionTempEntity {
모든 컬럼에 @Indexed가 포함된 이유가 있나요?

2024-02-11 15:23 UTC, belljun3395 commented on be/review-api/src/main/java/com/zzaug/review/web/controller/v1/member/MeController.java
page로 변환 과정을 controller 메서드에서 수행하기 보다는 별도의 클래스를 만들어 처리하는 것은 어떨까요?

2024-02-11 15:23 UTC, belljun3395 commented on be/review-api/src/main/java/com/zzaug/review/web/dto/question/QuestionRequest.java
> +	@NotEmpty private String content;
@NotBlank, @NotEmpty 둘다 필요하지 않을까요?

2024-02-11 15:23 UTC, belljun3395 commented on be/review-api/src/main/java/com/zzaug/review/web/dto/question/QuestionTempRequest.java
>  public class QuestionTempRequest {
@NotBlank, @NotEmpty 둘다 필요하지 않을까요?

2024-02-11 15:23 UTC, belljun3395 commented on be/review-api/src/main/java/com/zzaug/review/web/dto/question/QuestionViewRequest.java
> +	private Long questionId;
@NotBlank, @NotEmpty 둘다 필요하지 않을까요?

2024-02-12 05:59 UTC, sso9594 commented on be/review-api/src/main/java/com/zzaug/review/domain/dto/question/QuestionReqResponse.java
> +	private String[] requester;
리뷰 요청자를 보여주기 위해 있는 변수라 이름만으로 충분하다고 생각했는데, 저 요청자를 다시 사용할 여지가 있으면 id를 추가하는 것이 맞다고 생각해요

2024-02-12 06:00 UTC, sso9594 commented on be/review-api/src/main/java/com/zzaug/review/domain/model/member/ReviewerList.java
> +public class ReviewerList {
이벤트로 생성해야 하는 부분인데 아직 이벤트 listener를 만들지 않아서 사용되지 않고 있습니다

2024-02-12 06:01 UTC, sso9594 commented on be/review-api/src/main/java/com/zzaug/review/domain/model/question/Question.java
> +	private boolean isDeleted;
soft delete를 하기 위해 boolean 형식의 변수를 포함시켰습니다

2024-02-12 06:02 UTC, sso9594 commented on be/review-api/src/main/java/com/zzaug/review/domain/usecase/question/QuestionCreateUseCase.java
> +		questionRepository.save(QuestionEntityConverter.from(question));
저장할때는 멤버의 유효성과 request로 받은 객체의 유효성만 검사한다고 생각하여 controller에서 valid와 토큰 필터를 통한 유효성 검사 외에는 하지 않았습니다..!

2024-02-12 06:06 UTC, sso9594 commented on be/review-api/src/main/java/com/zzaug/review/domain/usecase/question/QuestionDeleteUseCase.java
> +		if (!question.getAuthorId().equals(request.getAuthorId())) {
일단 처음에 entity를 바로 사용하지 않고 분리 하기 위해 모델을 만들긴 했는데 사용하려고 보니 너무 많은 변환이 행해지는 것 같아 entity에서 정보를 받아 response를 하기 위한 객체로 변환하는 과정 하나만을 하기로 생각했습니다.

2024-02-12 06:07 UTC, sso9594 commented on be/review-api/src/main/java/com/zzaug/review/domain/usecase/question/QuestionReqViewUseCase.java
> +public class QuestionReqViewUseCase {
저도 다 적고 싶었는데 너무 길어지는 것 같아서 억지로 줄이긴 했네요 Request로 하는게 맞는 것 같습니다!

2024-02-12 06:08 UTC, sso9594 commented on be/review-api/src/main/java/com/zzaug/review/domain/usecase/question/QuestionReqViewUseCase.java
> +		LinkedHashSet<Long> reqQuestionIds = new LinkedHashSet<>();
중복 제거와 순서 보장을 위해 사용했습니다. 굳이 정렬과 중복제거에 코드를 짜는 것 보다 입력 받을 때 걸러 내는 것이 오버헤드를 적게 쓸 것 같다고 생각했습니다

2024-02-12 06:09 UTC, sso9594 commented on be/review-api/src/main/java/com/zzaug/review/domain/usecase/question/QuestionTempViewUseCase.java
> +			System.out.println(request.getTempId());
아 잘못 들어간 코드 같아요 죄송합니다 ㅎㅎ...

2024-02-12 06:11 UTC, sso9594 commented on be/review-api/src/main/java/com/zzaug/review/entity/member/ReviewerListEntity.java
> +public class ReviewerListEntity {
해당 엔티티는 추후에 이벤트 받고 다시 수정하려고 기본적인 폼만 만들어놨습니다.

2024-02-12 06:14 UTC, sso9594 commented on be/review-api/src/main/java/com/zzaug/review/entity/question/QuestionEntity.java
> +	private boolean isDeleted;
속성 명을 바꾸지 않으면 column을 사용하지 않아도 해당 변수 명으로 매핑 하기 때문에 안붙혀놓았습니다

2024-02-12 06:15 UTC, sso9594 commented on be/review-api/src/main/java/com/zzaug/review/entity/question/QuestionEntity.java
> +	@ColumnDefault("false")
이유는 딱히 없고.. 저장을 하는 흐름 이외에 따로 객체를 생성할 것 같지 않아서 저렇게 해놨습니다..!

2024-02-12 06:16 UTC, sso9594 commented on be/review-api/src/main/java/com/zzaug/review/entity/question/QuestionRequestEntity.java
> +public class QuestionRequestEntity {
이벤트 listener추가 할 때 같이 추가하겠습니다!

2024-02-12 06:17 UTC, sso9594 commented on be/review-api/src/main/java/com/zzaug/review/entity/question/QuestionTempEntity.java
> +public class QuestionTempEntity {
redis를 사용하기 위해 해당 속성들을 매핑하기 위해 indexed 어노테이션을 포함하였습니다!

2024-02-12 06:19 UTC, sso9594 commented on be/review-api/src/main/java/com/zzaug/review/web/controller/v1/member/MeController.java
converter로 빼놓으면 좋을 것 같네요 알겠습니다!

2024-02-12 06:21 UTC, sso9594 commented on be/review-api/src/main/java/com/zzaug/review/web/dto/question/QuestionRequest.java
> +	@NotEmpty private String content;
notblank를 사용했다가 " " 도 입력이라고 생각해서 notempty로 변경했었습니다!

2024-02-12 07:24 UTC, belljun3395 commented on be/review-api/src/main/java/com/zzaug/review/domain/model/question/Question.java
> +	private boolean isDeleted;
soft delete하려면 엔티티에 isdeleted가 필요한 것 아닌가요?

2024-02-19 08:13 UTC, merged