[Be/#49] Docs: 리뷰 서버 Mock API 구현
sgdevcamp2023/recycle pull request #84
Opened 2024-01-11 08:32 UTC by sso9594

🎫 연관 티켓 
---
#49 

🙏 작업
----
- API 명세에 따른 Mock 서버 구현하였습니다.

💁‍♂️ 어떻게?
----
- RestDocs를 활용하여 테스트를 통해 Swagger 문서를 만들 수 있도록 구성하였습니다.

로컬 개발 환경 구성 후 (scripts/recycle-develop-env-reset 실행)
``` 
./gradlew member-api:openapi3
```
위의 명령을 통해 openapi3을 생성할 수 있음

🙈 PR 참고 사항
----

📸 스크린샷
----

🤖 테스트 체크리스트
----
- [ ] 체크 미완료
- [x] 체크 완료

2024-01-11 17:06 UTC, belljun3395 reviewed
Query 서버랑, Command 서버랑 분리된 것으로 알고 있는데 Command 서버는 아직 작업하지 않은 것인가요?

2024-01-12 02:10 UTC, sso9594 reviewed
변경사항 확인해주세요
query서버는 review서버에서 먼저 다 만들고 브랜치로 남겨두고 분리해서 만들것 같습니다.

2024-01-12 02:15 UTC, belljun3395 commented on be/review-api/src/main/java/com/zzaug/review/web/dto/review/ReviewRequest.java
> +	private String location;
location은 이렇게 String 타입으로 받아도 괜찮을까요?
저희가 이야기 했을 때는 시작 인덱스, 종료 인덱스 형식으로 받기로 했던 것으로 기억해서요

2024-01-12 02:15 UTC, belljun3395 commented on be/review-api/src/main/java/com/zzaug/review/web/dto/review/ReviewTempRequest.java
> +	private String location;
위와 동일합니다.

2024-01-12 02:15 UTC, belljun3395 commented on be/review-api/src/main/java/com/zzaug/review/web/dto/review/ReviewTempRequest.java
> +	private String tag;
tag는 따로 enum을 지정하기 보다는 String으로 받을 예정인가요?

2024-01-12 02:15 UTC, belljun3395 commented on be/review-api/src/main/java/com/zzaug/review/domain/dto/review/ReviewResponse.java
> +	private String location;
이전 코멘트와 동일한 생각입니다.

2024-01-12 02:15 UTC, belljun3395 commented on be/review-api/src/main/java/com/zzaug/review/domain/dto/review/ReviewTempResponse.java
> +	private String location;
이전 코멘트와 동일한 생각입니다.

2024-01-12 02:18 UTC, belljun3395 commented
> 변경사항 확인해주세요 query서버는 review서버에서 먼저 다 만들고 브랜치로 남겨두고 분리해서 만들것 같습니다.

그렇게 진행하는 이유가 있나요?

두 서버의 모듈이 서로 달라서 추후 테스트 작성 및 확인하는 작업에서 불편함이 있을 것 같습니다.

2024-01-12 02:21 UTC, sso9594 commented on be/review-api/src/main/java/com/zzaug/review/web/dto/review/ReviewRequest.java
> +	private String location;
그 때 이야기 했을 때 그렇게 들어올것 같긴 한데 잘 모르겠다고 하셔서 일단 String으로 두긴 했어요

2024-01-12 02:23 UTC, sso9594 commented on be/review-api/src/main/java/com/zzaug/review/web/dto/review/ReviewTempRequest.java
> +	private String tag;
백에서는 구분할 필요가 없다고 생각했는데 생각해보니 깃 연동하게되면 필요하네요 enum으로 수정하겠습니다

2024-01-12 02:24 UTC, sso9594 commented
음 원래는 CQRS패턴으로 바꾸는 과정을 남기는 느낌으로 그런식으로 하려 했는데 굳이긴 하네요 분리해서 다시 올리겠습니다

2024-01-13 02:01 UTC, sso9594 reviewed
분리 했습니다 확인해주세요

2024-01-13 08:26 UTC, kor-Chipmunk commented on be/review-api/src/main/java/com/zzaug/review/domain/dto/review/ReviewResponse.java
> +	private Timestamp updated_at;
`java.time` 패키지의 `LocalDateTime` 대신 `java.sql` 패키지의 `Timestamp` 를 쓰는 이유가 혹시 있을까요!?

2024-01-13 14:46 UTC, sso9594 commented on be/review-api/src/main/java/com/zzaug/review/domain/dto/review/ReviewResponse.java
> +	private Timestamp updated_at;
아뇨 그냥 평소에 저렇게 해서  timestamp로 뒀어요..!

2024-01-14 05:29 UTC, belljun3395 requested changes

2024-01-14 05:29 UTC, belljun3395 commented on be/review-api/src/main/java/com/zzaug/review/web/controller/v1/comment/CommentController.java
> +		return ApiResponseGenerator.success(HttpStatus.OK);
Message 코드 enum을 이용해서 code와 message도 추가해줘야 할 것 같아요. 다른 컨트롤러도 동일합니다.

2024-01-14 05:29 UTC, belljun3395 commented on be/review-api/src/main/java/com/zzaug/review/web/dto/review/ReviewRequest.java
> +	private String location;
프런트 분들 멘션해서 확인하면 좋을 것 같아요

2024-01-14 05:29 UTC, belljun3395 commented on be/review-api/src/main/java/com/zzaug/review/web/dto/question/QuestionTempRequest.java
> +	private String t_id;
jackson 라이브러리가 추가되어 있는데 이를 활용해서 변수명은 tempId로 하고 요청 받는 것은 t_id로 할 수 있도록 수정해 보는 것은 어떨까요?

2024-01-14 05:29 UTC, belljun3395 commented on be/review-api/src/main/java/com/zzaug/review/web/dto/question/QuestionTempRequest.java
> +	private String t_id;
다른 _ 있는 변수명도 동일합니다. 저도 위와 같이 작성해 뒀는데 수정해야겠네요

2024-01-14 05:29 UTC, belljun3395 commented on be/review-api/src/test/java/com/zzaug/review/web/controller/v1/CommentControllerTest.java
> +															fieldWithPath("data").type(JsonFieldType.NULL).description("null"),
null이 반환되지 않도록 수정해 보는 것은 어떨까요?

2024-01-14 05:29 UTC, belljun3395 commented on be/review-api/src/test/java/com/zzaug/review/web/controller/v1/CommentControllerTest.java
> +								.header("Authorization", "{{accessToken")
{{accessToken 이네요 {{accessToken}}로 수정해야 할 것 같아요

2024-01-14 05:29 UTC, belljun3395 commented on be/review-api/src/test/java/com/zzaug/review/web/controller/v1/QuestionControllerTest.java
> +								.header("Authorization", "{{accessToken")
여기도 오타네요!

2024-01-14 05:29 UTC, belljun3395 commented on be/review-query-api/src/main/java/com/zzaug/review/web/controller/v1/ReviewQueryController.java
> +
여기는 왜 주석처리인가요? 사용하지 않으면 제거해도 좋을 것 같아요

2024-01-14 05:29 UTC, belljun3395 commented on be/review-query-api/src/test/java/com/zzaug/review/web/controller/v1/MeQueryControllerTest.java
> +								.header("Authorization", "{{accessToken")
오타네요

2024-01-14 05:29 UTC, belljun3395 commented on be/review-query-api/src/test/java/com/zzaug/review/web/controller/v1/MeQueryControllerTest.java
> +								.header("Authorization", "{{accessToken")
오타입니다

2024-01-16 05:59 UTC, belljun3395 approved these changes

2024-01-16 05:59 UTC, merged